server:
  port: 9901

eureka:
  instance:
    preferIpAddress: true
    instance-id: 127.0.0.1:9900
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:9900/eureka/

spring:
  application:
    name: server-service
  cloud:
    loadbalancer:
      retry:
        enabled: false