server:
  port: 9902

eureka:
  instance:
    preferIpAddress: true
    instance-id: 127.0.0.1:$9900
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:9900/eureka/

spring:
  application:
    name: web-service
  cloud:
    loadbalancer:
      retry:
        enabled: false